[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "aiosmtpd>=1.4.6",
    "flask>=3.1.0",
    "pydantic>=2.11.4",
    "python-dotenv>=1.1.0",
]
